<%@ Page Title="" Language="C#" MasterPageFile="~/Site/CibertecTemplate.master" AutoEventWireup="true" CodeBehind="ListArtist.aspx.cs" Inherits="WebFormCibertec.ArtistWeb.ListArtist" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ButtonContent" runat="server">
    <a class="btn btn-info" href="CreateArtist.aspx">
        Create Artist
    </a>
</asp:Content>

  <asp:Content ID="Content2" ContentPlaceHolderID="ArtistContent" runat="server">
    <div class="row">
        <h3>Artist List</h3>
    </div>
      <asp:UpdatePanel ID="ArtistUpdatePanel" runat="server">
          <ContentTemplate>
    <asp:SqlDataSource runat="server" ID="SqlDataSource"
        ConnectionString="<%$ ConnectionStrings:Cibertec %>"
        SelectCommand="GetListOfArtist"
        SelectCommandType="StoredProcedure"
        DeleteCommand="DeleteArtist"
         DeleteCommandType="StoredProcedure">

        <DeleteParameters>
            <asp:Parameter Name="ArtistId" Type="Int32" />
        </DeleteParameters>

    </asp:SqlDataSource>

    <div class="row-grid">
        <asp:GridView
            runat="server"
            ID="artistGriedView"
            DataKeyNames="ArtistId"
            AllowPaging="true"
            AllowSorting="true"
            AutoGenerateColumns="true"
            DataSourceID="SqlDataSource" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true"
            PageSize="20">

        </asp:GridView>
    </div>
          </ContentTemplate>
      </asp:UpdatePanel>

</asp:Content> 

